# Form implementation generated from reading ui file 'Curcon.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(350, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(350, 600))
        MainWindow.setMaximumSize(QtCore.QSize(350, 600))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/danle/OneDrive/Рабочий стол/pngwing.com.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(57, 0, 86);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.button_convert = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_convert.setGeometry(QtCore.QRect(10, 520, 330, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.button_convert.setFont(font)
        self.button_convert.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"border-color: #fb5b5d;\n"
"border-radius: 30;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(251, 91, 93);\n"
"}")
        self.button_convert.setObjectName("button_convert")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 351, 181))
        self.frame.setStyleSheet("background-color: rgb(251, 91, 93);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setIndent(3)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(125, 70, 100, 100))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/danle/OneDrive/Рабочий стол/aaa.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.line_old_currency = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_old_currency.setGeometry(QtCore.QRect(10, 200, 330, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.line_old_currency.setFont(font)
        self.line_old_currency.setStyleSheet("border: 2px solid;\n"
"border-color: #fb5b5d;\n"
"border-radius: 30;\n"
"color: white;\n"
"")
        self.line_old_currency.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.line_old_currency.setObjectName("line_old_currency")
        self.line_old_amount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_old_amount.setGeometry(QtCore.QRect(10, 280, 330, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.line_old_amount.setFont(font)
        self.line_old_amount.setStyleSheet("border: 2px solid;\n"
"border-color: #fb5b5d;\n"
"border-radius: 30;\n"
"color: white;\n"
"")
        self.line_old_amount.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.line_old_amount.setObjectName("line_old_amount")
        self.line_new_currency = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_new_currency.setGeometry(QtCore.QRect(10, 360, 330, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.line_new_currency.setFont(font)
        self.line_new_currency.setStyleSheet("border: 2px solid;\n"
"border-color: #fb5b5d;\n"
"border-radius: 30;\n"
"color: white;\n"
"")
        self.line_new_currency.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.line_new_currency.setObjectName("line_new_currency")
        self.line_new_amount = QtWidgets.QLabel(parent=self.centralwidget)
        self.line_new_amount.setGeometry(QtCore.QRect(10, 440, 330, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.line_new_amount.setFont(font)
        self.line_new_amount.setStyleSheet("border: 2px solid;\n"
"border-color: #fb5b5d;\n"
"border-radius: 30;\n"
"color: white;\n"
"")
        self.line_new_amount.setText("")
        self.line_new_amount.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.line_new_amount.setObjectName("line_new_amount")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Конвертер Валют"))
        self.button_convert.setText(_translate("MainWindow", "Конвертируй"))
        self.label.setText(_translate("MainWindow", "Конвертер валют"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
